package annotations

import (
	"github.com/apmckinlay/gsuneido/typechecker/typealgebra"
)

type methodTable struct {
	l        *loader
	receiver typealgebra.DynType
}

func (l *loader) methods(receiver typealgebra.DynType) *methodTable {
	return &methodTable{l: l, receiver: receiver}
}

func (t *methodTable) method(name, sig string) {
	s := mustParseSig(sig)
	s.Receiver = t.receiver
	if s.Returns == nil {
		s.Returns = typealgebra.TUnknown
	}
	t.l.register(name, s)
}

//nolint:funlen // flat data table of builtin signatures
func (l *loader) applyOverlay() {

	// ---- Object  ----
	ob := l.methods(typealgebra.TObject)
	ob.method("DeleteIf", "(block) :object")
	ob.method("FindAll", "(value) :object")
	ob.method("FindAllIf", "(block) :object")
	ob.method("Empty?", "() :boolean")
	ob.method("NotEmpty?", "() :boolean")
	ob.method("HasNamed?", "() :boolean")
	ob.method("Map!", "(block) :object")
	ob.method("Map", "(block) :object")
	ob.method("Map2", "(block) :object")
	ob.method("MapMembers", "(block) :object")
	ob.method("FlatMap", "(block) :object")
	ob.method("First", "() :unknown")
	ob.method("Last", "() :unknown")
	ob.method("MinWith", "(block) :unknown")
	ob.method("MaxWith", "(block) :unknown")
	ob.method("Project", "(@fields) :object")
	ob.method("ProjectValues", "(@fields) :object")
	ob.method("ListToNamed", "(@fields) :object")
	ob.method("ListToMembers", "() :object")
	ob.method("Flatten", "() :object")
	ob.method("Intersects?", "(other) :boolean")
	ob.method("Disjoint?", "(other) :boolean")
	ob.method("Intersect", "(other) :object")
	ob.method("Difference", "(other) :object")
	ob.method("Union", "(other) :object")
	ob.method("Subset?", "(other) :boolean")
	ob.method("MergeUnion", "(other) :object")
	ob.method("DuplicateValues", "() :object")
	ob.method("FindOne", "(block) :false|unknown")
	ob.method("FindIf", "(block) :false|unknown")
	ob.method("FindLastIf", "(block) :false|unknown")
	ob.method("MembersIf", "(block) :object")
	ob.method("Val_or_func", "(member) :unknown")
	ob.method("Merge", "(ob) :object")
	ob.method("MergeNew", "(ob) :object")
	ob.method("SafeMembers", "() :object")
	ob.method("Replace", "(oldvalue, newvalue) :object")
	ob.method("JoinCSV", "(fields = false) :string")
	ob.method("Sum", "() :number")
	ob.method("SumWith", "(block) :number")
	ob.method("Fold", "(val, block) :unknown")
	ob.method("Reduce", "(block) :unknown")
	ob.method("Remove1", "(x) :unknown")
	ob.method("Remove", "(@values) :object")
	ob.method("RemoveIf", "(block) :object")
	ob.method("Without", "(@values) :object")
	ob.method("WithoutFields", "(@fields) :object")
	ob.method("Swap", "(idx1, idx2) :object")
	ob.method("AddUnique", "(value) :object")
	ob.method("Filter", "(block) :object")
	ob.method("Zip", "() :object")
	ob.method("UniqueValues", "() :object")
	ob.method("Append", "(ob) :object")
	ob.method("Every?", "(block) :boolean")
	ob.method("Any?", "(block) :boolean")
	ob.method("HasIf?", "(block) :boolean")
	ob.method("Shuffle!", "() :object")
	ob.method("AddMany!", "(value, n) :object")
	ob.method("Each", "(block) :object")
	ob.method("Each2", "(block) :object")
	ob.method("SortWith!", "(block) :object")
	ob.method("Extract", "(member, x = #extract_no_default) :unknown")
	ob.method("Count", "(value = #(0)) :number")
	ob.method("CountIf", "(block) :number")
	ob.method("Sorted?", "(block = false) :boolean")
	ob.method("Trim!", "(@values) :object")
	ob.method("HasNonEmptyMember?", "(members) :boolean")
	ob.method("BinarySearch?", "(value) :boolean")
	ob.method("GetDifferences", "(ob) :object")
	ob.method("GetInit", "(member, block) :unknown")
	ob.method("Take", "(n) :object")
	ob.method("Drop", "(n) :object")
	ob.method("Nth", "(n) :unknown")
	ob.method("Concat", "(@iterables) :object")
	ob.method("AddTo", "(ob) :unknown")
	ob.method("Instantiate", "() :object")
	ob.method("Grep", "(regex, block = false) :object")
	ob.method("DeepCopy", "(nesting = 0) :object")
	ob.method("DeepReplaceReferences!", "(oldName, newName, nesting = 0) :unknown")
	ob.method("RandVal", "() :unknown")
	ob.method("EqualSet?", "(that) :boolean")

	// ---- String ----
	str := l.methods(typealgebra.TString)
	str.method("As", "(e) :string")
	str.method("LineCount", "() :number")
	str.method("FirstLine", "() :string")
	str.method("Lines", "() :object")
	str.method("RemoveBlankLines", "() :string")
	str.method("RemovePrefix", "(prefix) :string")
	str.method("RemoveSuffix", "(suffix) :string")
	str.method("ChangeEol", "(eol) :string")
	str.method("LineFromPosition", "(pos) :number")
	str.method("LineAtPosition", "(pos) :string")
	str.method("StartPositionOfLine", "(line) :number")
	str.method("Capitalize", "() :string")
	str.method("UnCapitalize", "() :string")
	str.method("CapitalizeWords", "(lower = true) :string")
	str.method("Trim", "(chars = ' \t\r\n') :string")
	str.method("LeftTrim", "(chars = ' \t\r\n') :string")
	str.method("RightTrim", "(chars = ' \t\r\n') :string")
	str.method("SplitCSV", "(fields = false, string_vals = false) :object")
	str.method("SplitFixedLength", "(map) :object")
	str.method("ReplaceSubstr", "(i, n, s) :string")
	str.method("LeftFill", "(minSize, char = ' ') :string")
	str.method("TruncateLeftFill", "(size, char = ' ') :string")
	str.method("RightFill", "(minSize, char = ' ') :string")
	str.method("TruncateRightFill", "(size, char = ' ') :string")
	str.method("Center", "(minSize, char = ' ') :string")
	str.method("SplitOnFirst", "(delimiter = ' ') :object")
	str.method("SplitOnLast", "(delimiter = ' ') :object")
	str.method("BeforeFirst", "(delimiter) :string")
	str.method("AfterFirst", "(delimiter) :string")
	str.method("BeforeLast", "(delimiter) :string")
	str.method("AfterLast", "(delimiter) :string")
	str.method("Capitalized?", "() :boolean")
	str.method("FindRx", "(rx) :number")
	str.method("FindRxLast", "(rx) :false|number")
	str.method("ExtractAll", "(pattern) :false|object")
	str.method("WrapLines", "(width) :object")
	str.method("Divide", "(n = 1) :object")
	str.method("White?", "() :boolean")
	str.method("Blank?", "() :boolean")
	str.method("In?", "(x) :boolean")
	str.method("Base64Encode", "() :string")
	str.method("Base64Decode", "() :string")
	str.method("Xor", "(key) :string")
	str.method("GlobalName?", "() :boolean")
	str.method("LocalName?", "() :boolean")
	str.method("Identifier?", "() :boolean")
	str.method("DynamicName?", "() :boolean")
	str.method("ForEachMatch", "(pat, block) :unknown")
	str.method("ForEach1of", "(chars, block) :unknown")
	str.method("SafeEval", "() :unknown")
	str.method("Map", "(block) :string")
	str.method("Escape", "() :string")
	str.method("Ellipsis", "(maxLength, atEnd = false) :string")
	str.method("Has1of?", "(chars) :boolean")
	str.method("UniqueChars", "() :string")
	str.method("StripInvalidChars", "() :string")
	str.method("RandChar", "() :string")
	str.method("Shuffle", "() :string")

	// ---- Number ----
	num := l.methods(typealgebra.TNumber)
	num.method("Ceiling", "() :number")
	num.method("Floor", "() :number")
	num.method("Abs", "() :number")
	num.method("PercentToDecimal", "() :number")
	num.method("DecimalToPercent", "(round = 0) :number")
	num.method("ToWords", "() :string")
	num.method("EnFrancais", "() :string")
	num.method("ToWordsFrench", "() :string")
	num.method("ToWordsDutch", "() :string")
	num.method("ToWordSpanish", "() :string")
	num.method("ToWordsItalian", "() :string")
	num.method("ToWordsSimple", "() :string")
	num.method("Pad", "(minSize, char = '0') :string")
	num.method("Factorial", "() :number")
	num.method("Int?", "() :boolean")
	num.method("IntDigits", "() :number")
	num.method("FracDigits", "() :number")
	num.method("EuroFormat", "(mask) :string")
	num.method("DollarFormat", "(mask) :string")
	num.method("Even?", "() :boolean")
	num.method("Odd?", "() :boolean")
	num.method("Sign", "() :number")
	num.method("RoundToPrecision", "(p) :number")
	num.method("RoundToNearest", "(nearest = 1) :number")
	num.method("ToRGB", "() :object")
	num.method("Times", "(block) :unknown")
	num.method("MinutesInMs", "() :number")
	num.method("SecondsInMs", "() :number")
	num.method("SecondsInHours", "() :number")
	num.method("HoursInSeconds", "() :number")
	num.method("HoursInMinutes", "() :number")
	num.method("SecondsInMinutes", "() :number")
	num.method("InchesInTwips", "() :number")
	num.method("TwipsInInch", "() :number")
	num.method("InchesInCanvasUnit", "() :number")
	num.method("Kb", "() :number")
	num.method("Mb", "() :number")
	num.method("Gb", "() :number")
	num.method("SafeEval", "() :number")
	num.method("Of", "(block) :object")
	num.method("OfStr", "(block) :string")

	// ---- Date ----
	date := l.methods(typealgebra.TDate)
	date.method("Format", "(format) :string")
	date.method("translate", "(s) :string")
	date.method("ShortDate", "() :string")
	date.method("LongDate", "() :string")
	date.method("Time", "() :string")
	date.method("DayOfYear", "() :number")
	date.method("NoTime", "() :date")
	date.method("NoTime?", "() :boolean")
	date.method("StartOfDay", "() :date")
	date.method("EndOfDay", "() :date")
	date.method("Replace", "(@args) :date")
	date.method("MinusMinutes", "(date) :number")
	date.method("MinusHours", "(date) :number")
	date.method("MinusMonths", "(date) :number")
	date.method("ShortDateTime", "() :string")
	date.method("ShortDateTimeSec", "() :string")
	date.method("StdShortDate", "() :string")
	date.method("StdShortDateTime", "() :string")
	date.method("StdShortDateTimeSec", "() :string")
	date.method("LongDateTime", "() :string")
	date.method("StartOfYear", "() :date")
	date.method("EndOfMonth", "() :date")
	date.method("EndOfMonthDay", "() :number")
	date.method("WeekNumber", "(firstday = 'sun') :number")
	date.method("WeekStart", "(firstday = 'sun') :date")
	date.method("Quarter", "() :number")
	date.method("IsoWeekDay", "() :string")
	date.method("isLeapYear?", "(year) :boolean")
	date.method("GMTime", "() :date")
	date.method("GMTimeToLocal", "() :date")
	date.method("UTC", "(gmtBias = false) :string")
	date.method("Minus", "(@args) :date")
	date.method("InternetFormat", "() :string")
	date.method("UnixTime", "() :number")
	date.method("FromUnix", "(s) :date")

	class := l.methods(typealgebra.TClass)
	class.method("Base", "() :unknown")
	class.method("Eval", "(@args) :unknown")
	class.method("Eval2", "(@args) :object")
	class.method("GetDefault", "(member, block) :unknown")
	class.method("Member?", "(member) :boolean")
	class.method("Members", "(all = false) :object")
	class.method("Size", "() :number")
	class.method("Synchronized", "(block) :unknown")
}
